name: Log Live Binance Data

on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script
        run: python fetch_live_data.py

      - name: Commit updated CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add live_*.csv
          git commit -m "Update live data" || echo "No changes"
          git push
